import Foundation

/// A file generated by the model. Mirrors upstream `GeneratedFile`.
public struct GeneratedFile: Sendable, Equatable {
  /// The file content as bytes.
  public let data: Data
  /// IANA media type of the file.
  public let mediaType: String

  public init(data: Data, mediaType: String) {
    self.data = data
    self.mediaType = mediaType
  }

  /// The file content as base64.
  public var base64: String { data.base64EncodedString() }
}

/// A tool call in a step. Mirrors upstream `TypedToolCall` (static and dynamic).
public struct ToolCall: Sendable {
  public var toolCallId: String
  public var toolName: String
  /// The parsed input. For invalid calls, the raw input.
  public var input: JSONValue
  public var providerExecuted: Bool?
  /// Whether the tool is dynamic (or the call is invalid).
  public var dynamic: Bool
  /// Whether the call could not be parsed or validated.
  public var invalid: Bool
  /// Why the call is invalid.
  public var error: (any Error)?
  public var title: String?
  public var providerMetadata: ProviderMetadata?
  public var toolMetadata: JSONObject?

  public init(
    toolCallId: String,
    toolName: String,
    input: JSONValue,
    providerExecuted: Bool? = nil,
    dynamic: Bool = false,
    invalid: Bool = false,
    error: (any Error)? = nil,
    title: String? = nil,
    providerMetadata: ProviderMetadata? = nil,
    toolMetadata: JSONObject? = nil
  ) {
    self.toolCallId = toolCallId
    self.toolName = toolName
    self.input = input
    self.providerExecuted = providerExecuted
    self.dynamic = dynamic
    self.invalid = invalid
    self.error = error
    self.title = title
    self.providerMetadata = providerMetadata
    self.toolMetadata = toolMetadata
  }
}

/// A tool result in a step. Mirrors upstream `TypedToolResult`.
public struct ToolResult: Sendable, Equatable {
  public var toolCallId: String
  public var toolName: String
  public var input: JSONValue
  public var output: JSONValue
  public var providerExecuted: Bool?
  public var dynamic: Bool
  /// Preliminary results are superseded by the final result.
  public var preliminary: Bool
  public var providerMetadata: ProviderMetadata?
  public var toolMetadata: JSONObject?

  public init(
    toolCallId: String,
    toolName: String,
    input: JSONValue,
    output: JSONValue,
    providerExecuted: Bool? = nil,
    dynamic: Bool = false,
    preliminary: Bool = false,
    providerMetadata: ProviderMetadata? = nil,
    toolMetadata: JSONObject? = nil
  ) {
    self.toolCallId = toolCallId
    self.toolName = toolName
    self.input = input
    self.output = output
    self.providerExecuted = providerExecuted
    self.dynamic = dynamic
    self.preliminary = preliminary
    self.providerMetadata = providerMetadata
    self.toolMetadata = toolMetadata
  }
}

/// A failed tool execution. Mirrors upstream `TypedToolError`.
public struct ToolError: Sendable {
  public var toolCallId: String
  public var toolName: String
  public var input: JSONValue
  public var error: any Error
  public var providerExecuted: Bool?
  public var dynamic: Bool
  public var providerMetadata: ProviderMetadata?
  public var toolMetadata: JSONObject?

  public init(
    toolCallId: String,
    toolName: String,
    input: JSONValue,
    error: any Error,
    providerExecuted: Bool? = nil,
    dynamic: Bool = false,
    providerMetadata: ProviderMetadata? = nil,
    toolMetadata: JSONObject? = nil
  ) {
    self.toolCallId = toolCallId
    self.toolName = toolName
    self.input = input
    self.error = error
    self.providerExecuted = providerExecuted
    self.dynamic = dynamic
    self.providerMetadata = providerMetadata
    self.toolMetadata = toolMetadata
  }
}

/// The outcome of executing a tool call.
public enum ToolOutput: Sendable {
  case result(ToolResult)
  case error(ToolError)

  public var toolCallId: String {
    switch self {
    case .result(let result): result.toolCallId
    case .error(let error): error.toolCallId
    }
  }
}

/// A request for approval of a tool call. Mirrors upstream `ToolApprovalRequestOutput`.
public struct ToolApprovalRequestOutput: Sendable {
  public var approvalId: String
  public var toolCall: ToolCall
  public var reason: String?
  public var isAutomatic: Bool?
  public var signature: String?

  public init(
    approvalId: String, toolCall: ToolCall, reason: String? = nil, isAutomatic: Bool? = nil,
    signature: String? = nil
  ) {
    self.approvalId = approvalId
    self.toolCall = toolCall
    self.reason = reason
    self.isAutomatic = isAutomatic
    self.signature = signature
  }
}

/// An approval decision for a tool call. Mirrors upstream `ToolApprovalResponseOutput`.
public struct ToolApprovalResponseOutput: Sendable {
  public var approvalId: String
  public var toolCall: ToolCall
  public var approved: Bool
  public var reason: String?
  public var providerExecuted: Bool?

  public init(
    approvalId: String, toolCall: ToolCall, approved: Bool, reason: String? = nil, providerExecuted: Bool? = nil
  ) {
    self.approvalId = approvalId
    self.toolCall = toolCall
    self.approved = approved
    self.reason = reason
    self.providerExecuted = providerExecuted
  }
}

/// A source used for generation. Mirrors upstream `Source`.
public typealias Source = LanguageModelV4Source

/// Reasoning generated by the model. Mirrors upstream `ReasoningOutput`.
public struct ReasoningOutput: Sendable, Equatable {
  public var text: String
  public var providerMetadata: ProviderMetadata?

  public init(text: String, providerMetadata: ProviderMetadata? = nil) {
    self.text = text
    self.providerMetadata = providerMetadata
  }
}

/// Content generated in a step. Mirrors upstream `ContentPart`.
public enum ContentPart: Sendable {
  case text(String, providerMetadata: ProviderMetadata? = nil)
  case reasoning(ReasoningOutput)
  case custom(kind: String, providerMetadata: ProviderMetadata? = nil)
  case source(Source)
  case file(GeneratedFile, providerMetadata: ProviderMetadata? = nil)
  case reasoningFile(GeneratedFile, providerMetadata: ProviderMetadata? = nil)
  case toolCall(ToolCall)
  case toolResult(ToolResult)
  case toolError(ToolError)
  case toolApprovalRequest(ToolApprovalRequestOutput)
  case toolApprovalResponse(ToolApprovalResponseOutput)
}

extension FileData {
  /// Decodes generated file data into bytes.
  func generatedBytes() -> Data {
    switch self {
    case .data(let data): data
    case .base64(let base64): convertBase64ToData(base64) ?? Data()
    case .text(let text): Data(text.utf8)
    case .url, .reference: Data()
    }
  }
}

/// Converts model output content, merging in tool calls, outputs and
/// approvals. Mirrors upstream `convertLanguageModelContent`.
func convertLanguageModelContent(
  content: [LanguageModelV4Content],
  toolCalls: [ToolCall],
  toolOutputs: [ToolOutput],
  toolApprovalRequests: [ToolApprovalRequestOutput],
  toolApprovalResponses: [ToolApprovalResponseOutput],
  tools: ToolSet?
) -> [ContentPart] {
  var parts: [ContentPart] = []
  for part in content {
    switch part {
    case .text(let text):
      parts.append(.text(text.text, providerMetadata: text.providerMetadata))
    case .reasoning(let reasoning):
      parts.append(.reasoning(ReasoningOutput(text: reasoning.text, providerMetadata: reasoning.providerMetadata)))
    case .custom(let custom):
      parts.append(.custom(kind: custom.kind, providerMetadata: custom.providerMetadata))
    case .source(let source):
      parts.append(.source(source))
    case .file(let file):
      parts.append(
        .file(
          GeneratedFile(data: file.data.generatedBytes(), mediaType: file.mediaType),
          providerMetadata: file.providerMetadata))
    case .reasoningFile(let file):
      parts.append(
        .reasoningFile(
          GeneratedFile(data: file.data.generatedBytes(), mediaType: file.mediaType),
          providerMetadata: file.providerMetadata))
    case .toolCall(let call):
      if let parsed = toolCalls.first(where: { $0.toolCallId == call.toolCallId }) {
        parts.append(.toolCall(parsed))
      }
    case .toolResult(let result):
      let call = toolCalls.first { $0.toolCallId == result.toolCallId }
      let input = call?.input ?? .null
      let dynamic = result.dynamic ?? call?.dynamic ?? false
      if result.isError == true {
        parts.append(
          .toolError(
            ToolError(
              toolCallId: result.toolCallId, toolName: result.toolName, input: input,
              error: ProviderToolError(value: result.result), providerExecuted: true, dynamic: dynamic,
              providerMetadata: result.providerMetadata)))
      } else {
        parts.append(
          .toolResult(
            ToolResult(
              toolCallId: result.toolCallId, toolName: result.toolName, input: input, output: result.result,
              providerExecuted: true, dynamic: dynamic, preliminary: result.preliminary ?? false,
              providerMetadata: result.providerMetadata)))
      }
    case .toolApprovalRequest(let request):
      if let call = toolCalls.first(where: { $0.toolCallId == request.toolCallId }) {
        parts.append(.toolApprovalRequest(ToolApprovalRequestOutput(approvalId: request.approvalId, toolCall: call)))
      }
    }
  }
  parts += toolApprovalRequests.map(ContentPart.toolApprovalRequest)
  parts += toolApprovalResponses.map(ContentPart.toolApprovalResponse)
  parts += toolOutputs.map { output in
    switch output {
    case .result(let result): .toolResult(result)
    case .error(let error): .toolError(error)
    }
  }
  return parts
}

/// An error result reported by a provider-executed tool.
public struct ProviderToolError: AISDKError {
  public let name = "AI_ProviderToolError"
  public let value: JSONValue

  public init(value: JSONValue) {
    self.value = value
  }

  public var message: String { value.stringValue ?? value.jsonString() }
}
