import Foundation

private let defaultGenerateId: IdGenerator = {
  try! createIdGenerator(prefix: "aitxt", size: 24)
}()

/// The result of `generateText`. Mirrors upstream `GenerateTextResult`.
///
/// `OutputValue` is the type of `output`: `String` for plain text, or the
/// parsed value of the `Output` passed to `generateText`.
public struct GenerateTextResult<OutputValue: Sendable>: Sendable {
  /// All steps, in order.
  public let steps: [StepResult]
  /// Usage summed over all steps.
  public let totalUsage: LanguageModelUsage
  let initialResponseMessages: [ModelMessage]
  let resolvedOutput: OutputValue?

  init(
    steps: [StepResult], totalUsage: LanguageModelUsage, initialResponseMessages: [ModelMessage],
    output: OutputValue?
  ) {
    self.steps = steps
    self.totalUsage = totalUsage
    self.initialResponseMessages = initialResponseMessages
    self.resolvedOutput = output
  }

  /// The parsed output of the final step.
  ///
  /// - Throws: `NoOutputGeneratedError` when the final step ended with tool
  ///   calls or without text, so there was nothing to parse.
  public var output: OutputValue {
    get throws {
      guard let resolvedOutput else { throw NoOutputGeneratedError() }
      return resolvedOutput
    }
  }

  /// The last step.
  public var finalStep: StepResult { steps[steps.count - 1] }

  /// Content from all steps.
  public var content: [ContentPart] { steps.flatMap(\.content) }
  /// The text of the last step.
  public var text: String { finalStep.text }
  public var reasoning: [ReasoningOutput] { finalStep.reasoning }
  public var reasoningText: String? { finalStep.reasoningText }
  public var files: [GeneratedFile] { steps.flatMap(\.files) }
  public var sources: [Source] { steps.flatMap(\.sources) }
  public var toolCalls: [ToolCall] { steps.flatMap(\.toolCalls) }
  public var staticToolCalls: [ToolCall] { steps.flatMap(\.staticToolCalls) }
  public var dynamicToolCalls: [ToolCall] { steps.flatMap(\.dynamicToolCalls) }
  public var toolResults: [ToolResult] { steps.flatMap(\.toolResults) }
  public var staticToolResults: [ToolResult] { steps.flatMap(\.staticToolResults) }
  public var dynamicToolResults: [ToolResult] { steps.flatMap(\.dynamicToolResults) }
  public var finishReason: FinishReason { finalStep.finishReason }
  public var rawFinishReason: String? { finalStep.rawFinishReason }
  public var warnings: [Warning] { steps.flatMap(\.warnings) }
  public var providerMetadata: ProviderMetadata? { finalStep.providerMetadata }
  public var request: LanguageModelRequestMetadata { finalStep.request }
  public var response: LanguageModelResponseMetadata { finalStep.response }
  /// Same as `totalUsage`.
  public var usage: LanguageModelUsage { totalUsage }

  /// Messages generated by the call, ready to append to the conversation.
  public var responseMessages: [ModelMessage] {
    initialResponseMessages + steps.flatMap(\.response.messages)
  }
}

/// Generates text and calls tools with a language model. Mirrors upstream `generateText`.
///
/// Runs a loop of model calls: after each step with executable tool calls, the
/// tool results are sent back to the model, until the model stops calling
/// tools or a stop condition in `stopWhen` is met.
///
/// - Parameters:
///   - model: The language model.
///   - instructions: System instructions.
///   - prompt: A text prompt or a list of messages.
///   - tools: Tools the model can call.
///   - toolChoice: How the model selects tools. Defaults to `.auto`.
///   - activeTools: Restricts which tools are available without changing types.
///   - stopWhen: Stop conditions for multi-step calls. Defaults to one step.
///   - prepareStep: Adjusts settings before each step.
///   - repairToolCall: Repairs tool calls that fail to parse.
///   - toolApproval: Decides which tool calls need approval.
///   - toolsContext: Context passed to tools, keyed by tool name.
public func generateText<Value, Partial, Element>(
  model: LanguageModel,
  instructions: Instructions? = nil,
  prompt: Prompt,
  allowSystemInMessages: Bool = false,
  tools: ToolSet? = nil,
  toolChoice: ToolChoice? = nil,
  activeTools: [String]? = nil,
  toolOrder: [String]? = nil,
  output: Output<Value, Partial, Element>,
  maxOutputTokens: Int? = nil,
  temperature: Double? = nil,
  topP: Double? = nil,
  topK: Int? = nil,
  presencePenalty: Double? = nil,
  frequencyPenalty: Double? = nil,
  stopSequences: [String]? = nil,
  seed: Int? = nil,
  reasoning: LanguageModelV4ReasoningEffort? = nil,
  maxRetries: Int = 2,
  headers: [String: String]? = nil,
  providerOptions: ProviderOptions? = nil,
  stopWhen: [StopCondition] = [.isStepCount(1)],
  prepareStep: PrepareStepFunction? = nil,
  repairToolCall: ToolCallRepairFunction? = nil,
  toolApproval: ToolApprovalConfiguration? = nil,
  toolsContext: [String: JSONValue]? = nil,
  download: DownloadFunction? = nil,
  include: IncludeOptions = IncludeOptions(),
  generateId: IdGenerator? = nil,
  currentDate: @escaping @Sendable () -> Date = Date.init,
  onStepFinish: (@Sendable (StepResult) async -> Void)? = nil,
  onFinish: (@Sendable (GenerateTextResult<Value>) async -> Void)? = nil
) async throws -> GenerateTextResult<Value> {
  let generateId = generateId ?? defaultGenerateId
  let callSettings = try CallSettings(
    maxOutputTokens: maxOutputTokens, temperature: temperature, topP: topP, topK: topK,
    presencePenalty: presencePenalty, frequencyPenalty: frequencyPenalty, stopSequences: stopSequences, seed: seed,
    reasoning: reasoning, maxRetries: maxRetries, headers: headers
  ).validated()
  let retry = prepareRetries(maxRetries: callSettings.maxRetries)
  let initialPrompt = try standardizePrompt(
    instructions: instructions, prompt: prompt, allowSystemInMessages: allowSystemInMessages)
  let initialMessages = initialPrompt.messages
  var toolsContext = toolsContext

  var initialResponseMessages: [ModelMessage] = []
  let approvals = try collectToolApprovals(messages: initialMessages)
  let localApproved = approvals.approved.filter { $0.toolCall.providerExecuted != true }
  let deniedWithoutResults = approvals.denied.filter { $0.existingToolResult == nil }

  if !localApproved.isEmpty || !deniedWithoutResults.isEmpty {
    let outputs = try await executeTools(
      localApproved.map(\.toolCall), tools: tools, messages: initialMessages, toolsContext: toolsContext)

    var toolContent: [ToolContentPart] = []
    for output in outputs {
      switch output {
      case .result(let result):
        toolContent.append(
          .toolResult(
            ToolResultPart(
              toolCallId: result.toolCallId, toolName: result.toolName,
              output: try await createToolModelOutput(
                toolCallId: result.toolCallId, input: result.input, output: result.output,
                tool: tools?[result.toolName], errorMode: .none))))
      case .error(let error):
        toolContent.append(
          .toolResult(
            ToolResultPart(
              toolCallId: error.toolCallId, toolName: error.toolName,
              output: .errorText(getErrorMessage(error.error)))))
      }
    }
    for approval in deniedWithoutResults {
      let options: ProviderOptions? =
        approval.toolCall.providerExecuted == true
        ? ["openai": ["approvalId": .string(approval.approvalResponse.approvalId)]] : nil
      toolContent.append(
        .toolResult(
          ToolResultPart(
            toolCallId: approval.toolCall.toolCallId, toolName: approval.toolCall.toolName,
            output: .executionDenied(reason: approval.approvalResponse.reason, providerOptions: options))))
    }
    initialResponseMessages.append(.tool(toolContent))
  }

  var steps: [StepResult] = []
  var instructionsForNextStep = initialPrompt.instructions
  var messagesForNextStep = initialMessages + initialResponseMessages
  var pendingDeferredToolCalls: [String: String] = [:]
  var clientToolCalls: [ToolCall] = []
  var clientToolOutputs: [ToolOutput] = []
  var deniedToolApprovalResponses: [ToolApprovalResponseOutput] = []

  while true {
    if !steps.isEmpty { try Task.checkCancellation() }
    let stepNumber = steps.count
    let accumulatedResponseMessages = initialResponseMessages + steps.flatMap(\.response.messages)

    let prepared = try await prepareStep?(
      PrepareStepOptions(
        steps: steps, stepNumber: stepNumber, model: model, instructions: instructionsForNextStep,
        initialInstructions: initialPrompt.instructions, messages: messagesForNextStep,
        initialMessages: initialMessages, responseMessages: accumulatedResponseMessages,
        toolsContext: toolsContext))

    let stepModel = prepared?.model ?? model
    let stepInstructions = prepared?.instructions ?? instructionsForNextStep
    toolsContext = prepared?.toolsContext ?? toolsContext
    let stepTools = tools?.filtered(to: prepared?.activeTools ?? activeTools)
    let stepToolChoice = (prepared?.toolChoice ?? toolChoice ?? .auto).languageModelToolChoice
    let stepMessages = prepared?.messages ?? messagesForNextStep

    let promptMessages = try await convertToLanguageModelPrompt(
      prompt: StandardizedPrompt(instructions: stepInstructions, messages: stepMessages),
      supportedUrls: try await stepModel.supportedUrls,
      download: download)

    var callOptions = (prepared?.apply(to: callSettings) ?? callSettings).callOptions(prompt: promptMessages)
    callOptions.tools = prepareTools(stepTools, toolOrder: prepared?.toolOrder ?? toolOrder)
    callOptions.toolChoice = stepToolChoice
    callOptions.providerOptions = mergeProviderOptions(providerOptions, prepared?.providerOptions)
    callOptions.responseFormat = output.name == "text" ? nil : output.responseFormat
    let stepCallOptions = callOptions

    let modelResult = try await retry { try await stepModel.doGenerate(stepCallOptions) }
    let responseId = modelResult.response?.id ?? generateId()
    let responseTimestamp = modelResult.response?.metadata.timestamp ?? currentDate()
    let responseModelId = modelResult.response?.modelId ?? stepModel.modelId

    var stepToolCalls: [ToolCall] = []
    for case .toolCall(let call) in modelResult.content {
      stepToolCalls.append(
        try await parseToolCall(
          call, tools: stepTools, repairToolCall: repairToolCall, instructions: stepInstructions,
          messages: stepMessages))
    }

    switch stepToolChoice {
    case .required where stepToolCalls.isEmpty:
      throw ToolChoiceViolationError(
        toolChoice: stepToolChoice, finishReason: modelResult.finishReason.unified,
        provider: stepModel.provider, modelId: stepModel.modelId, content: modelResult.content)
    case .tool(let name) where !stepToolCalls.contains(where: { $0.toolName == name }):
      throw ToolChoiceViolationError(
        toolChoice: stepToolChoice, finishReason: modelResult.finishReason.unified,
        provider: stepModel.provider, modelId: stepModel.modelId, content: modelResult.content)
    default:
      break
    }

    var approvalRequests: [ToolApprovalRequestOutput] = []
    var approvalResponses: [ToolApprovalResponseOutput] = []
    var blockedToolCallIds = Set<String>()

    for toolCall in stepToolCalls where !toolCall.invalid {
      guard let tool = stepTools?[toolCall.toolName] else { continue }

      let executionOptions = ToolExecutionOptions(
        toolCallId: toolCall.toolCallId, messages: stepMessages, context: toolsContext?[toolCall.toolName])
      await tool.onInputStart?(executionOptions)
      await tool.onInputAvailable?(toolCall.input, executionOptions)

      let status = try await resolveToolApproval(
        toolCall: toolCall, tools: stepTools, configuration: toolApproval, messages: stepMessages,
        toolsContext: toolsContext)
      if status == .notApplicable { continue }

      let approvalId = generateId()
      switch status {
      case .notApplicable:
        break
      case .userApproval(let reason):
        approvalRequests.append(ToolApprovalRequestOutput(approvalId: approvalId, toolCall: toolCall, reason: reason))
        blockedToolCallIds.insert(toolCall.toolCallId)
      case .approved(let reason):
        approvalRequests.append(ToolApprovalRequestOutput(approvalId: approvalId, toolCall: toolCall, isAutomatic: true))
        approvalResponses.append(
          ToolApprovalResponseOutput(
            approvalId: approvalId, toolCall: toolCall, approved: true, reason: reason,
            providerExecuted: toolCall.providerExecuted))
      case .denied(let reason):
        approvalRequests.append(ToolApprovalRequestOutput(approvalId: approvalId, toolCall: toolCall, isAutomatic: true))
        approvalResponses.append(
          ToolApprovalResponseOutput(
            approvalId: approvalId, toolCall: toolCall, approved: false, reason: reason,
            providerExecuted: toolCall.providerExecuted))
        blockedToolCallIds.insert(toolCall.toolCallId)
      }
    }

    clientToolOutputs = stepToolCalls
      .filter { $0.invalid && $0.dynamic && $0.providerExecuted != true }
      .map { call in
        .error(
          ToolError(
            toolCallId: call.toolCallId, toolName: call.toolName, input: call.input,
            error: call.error ?? NoOutputGeneratedError(), dynamic: true))
      }
    clientToolCalls = stepToolCalls.filter { $0.providerExecuted != true }
    deniedToolApprovalResponses = approvalResponses.filter { !$0.approved }

    if let stepTools, isToolExecutionAllowed(modelResult.finishReason.unified) {
      clientToolOutputs += try await executeTools(
        clientToolCalls.filter { !$0.invalid && !blockedToolCallIds.contains($0.toolCallId) },
        tools: stepTools, messages: stepMessages, toolsContext: toolsContext)
    }

    for toolCall in stepToolCalls where toolCall.providerExecuted == true {
      guard let info = stepTools?[toolCall.toolName]?.providerToolInfo, info.supportsDeferredResults else { continue }
      let hasResult = modelResult.content.contains {
        if case .toolResult(let result) = $0 { return result.toolCallId == toolCall.toolCallId }
        return false
      }
      if !hasResult { pendingDeferredToolCalls[toolCall.toolCallId] = toolCall.toolName }
    }
    for case .toolResult(let result) in modelResult.content {
      pendingDeferredToolCalls.removeValue(forKey: result.toolCallId)
    }

    let stepContent = convertLanguageModelContent(
      content: modelResult.content, toolCalls: stepToolCalls, toolOutputs: clientToolOutputs,
      toolApprovalRequests: approvalRequests, toolApprovalResponses: approvalResponses, tools: tools)
    let stepResponseMessages = try await toResponseMessages(content: stepContent, tools: tools)

    let step = StepResult(
      stepNumber: stepNumber,
      provider: stepModel.provider,
      modelId: stepModel.modelId,
      content: stepContent,
      finishReason: modelResult.finishReason.unified,
      rawFinishReason: modelResult.finishReason.raw,
      usage: LanguageModelUsage(modelResult.usage),
      warnings: modelResult.warnings,
      request: LanguageModelRequestMetadata(
        body: include.requestBody ? modelResult.request?.body : nil,
        messages: include.requestMessages ? stepMessages : nil),
      response: LanguageModelResponseMetadata(
        id: responseId, timestamp: responseTimestamp, modelId: responseModelId,
        headers: modelResult.response?.headers,
        body: include.responseBody ? modelResult.response?.body : nil,
        messages: stepResponseMessages),
      providerMetadata: modelResult.providerMetadata)

    steps.append(step)
    instructionsForNextStep = stepInstructions
    messagesForNextStep = stepMessages + stepResponseMessages
    await onStepFinish?(step)

    // Continue only once every client tool call has an output or a denial.
    let allToolCallsResolved =
      clientToolOutputs.count + deniedToolApprovalResponses.count == clientToolCalls.count
    let hasPendingWork = !clientToolCalls.isEmpty || !pendingDeferredToolCalls.isEmpty
    guard allToolCallsResolved, hasPendingWork, !(await isStopConditionMet(stopWhen, steps: steps)) else {
      break
    }
  }

  let totalUsage = steps.reduce(LanguageModelUsage()) { $0 + $1.usage }
  let lastStep = steps[steps.count - 1]
  let resolvedOutput = try shouldParseOutput(lastStep) ? output.parseCompleteOutput(lastStep.text, context: OutputContext(lastStep)) : nil
  let result = GenerateTextResult(
    steps: steps, totalUsage: totalUsage, initialResponseMessages: initialResponseMessages, output: resolvedOutput)
  await onFinish?(result)
  return result
}

/// Generates text and calls tools with a language model. Mirrors upstream
/// `generateText` without an `output` setting; `result.output` is the text.
public func generateText(
  model: LanguageModel,
  instructions: Instructions? = nil,
  prompt: Prompt,
  allowSystemInMessages: Bool = false,
  tools: ToolSet? = nil,
  toolChoice: ToolChoice? = nil,
  activeTools: [String]? = nil,
  toolOrder: [String]? = nil,
  maxOutputTokens: Int? = nil,
  temperature: Double? = nil,
  topP: Double? = nil,
  topK: Int? = nil,
  presencePenalty: Double? = nil,
  frequencyPenalty: Double? = nil,
  stopSequences: [String]? = nil,
  seed: Int? = nil,
  reasoning: LanguageModelV4ReasoningEffort? = nil,
  maxRetries: Int = 2,
  headers: [String: String]? = nil,
  providerOptions: ProviderOptions? = nil,
  stopWhen: [StopCondition] = [.isStepCount(1)],
  prepareStep: PrepareStepFunction? = nil,
  repairToolCall: ToolCallRepairFunction? = nil,
  toolApproval: ToolApprovalConfiguration? = nil,
  toolsContext: [String: JSONValue]? = nil,
  download: DownloadFunction? = nil,
  include: IncludeOptions = IncludeOptions(),
  generateId: IdGenerator? = nil,
  currentDate: @escaping @Sendable () -> Date = Date.init,
  onStepFinish: (@Sendable (StepResult) async -> Void)? = nil,
  onFinish: (@Sendable (GenerateTextResult<String>) async -> Void)? = nil
) async throws -> GenerateTextResult<String> {
  try await generateText(
    model: model, instructions: instructions, prompt: prompt, allowSystemInMessages: allowSystemInMessages,
    tools: tools, toolChoice: toolChoice, activeTools: activeTools, toolOrder: toolOrder, output: .text(),
    maxOutputTokens: maxOutputTokens, temperature: temperature, topP: topP, topK: topK,
    presencePenalty: presencePenalty, frequencyPenalty: frequencyPenalty, stopSequences: stopSequences, seed: seed,
    reasoning: reasoning, maxRetries: maxRetries, headers: headers, providerOptions: providerOptions,
    stopWhen: stopWhen, prepareStep: prepareStep, repairToolCall: repairToolCall, toolApproval: toolApproval,
    toolsContext: toolsContext, download: download, include: include, generateId: generateId,
    currentDate: currentDate, onStepFinish: onStepFinish, onFinish: onFinish)
}

/// Output is parsed for stop responses and for non-empty responses that are
/// not tool calls. Mirrors upstream `generateText`.
func shouldParseOutput(_ step: StepResult) -> Bool {
  step.finishReason == .stop || (step.finishReason != .toolCalls && !step.text.isEmpty)
}

extension OutputContext {
  init(_ step: StepResult) {
    var response = step.response
    response.messages = []
    response.body = nil
    self.init(response: response, usage: step.usage, finishReason: step.finishReason)
  }
}

/// Tools only run when the model finished normally. Mirrors upstream
/// `isToolExecutionAllowedFinishReason`.
func isToolExecutionAllowed(_ finishReason: FinishReason) -> Bool {
  finishReason == .stop || finishReason == .toolCalls
}
