import Foundation

/// Options passed to `prepareStep`. Mirrors upstream `PrepareStepFunction` options.
public struct PrepareStepOptions: Sendable {
  public var steps: [StepResult]
  public var stepNumber: Int
  public var model: LanguageModel
  public var instructions: Instructions?
  public var initialInstructions: Instructions?
  /// The messages that will be sent in this step.
  public var messages: [ModelMessage]
  public var initialMessages: [ModelMessage]
  /// Messages generated by previous steps.
  public var responseMessages: [ModelMessage]
  public var toolsContext: [String: JSONValue]?
}

/// Per-step overrides returned by `prepareStep`. Mirrors upstream `PrepareStepResult`.
public struct PrepareStepResult: Sendable {
  public var model: LanguageModel?
  public var toolChoice: ToolChoice?
  public var activeTools: [String]?
  public var toolOrder: [String]?
  public var instructions: Instructions?
  public var messages: [ModelMessage]?
  public var toolsContext: [String: JSONValue]?
  public var providerOptions: ProviderOptions?
  public var maxOutputTokens: Int?
  public var temperature: Double?
  public var topP: Double?
  public var topK: Int?
  public var presencePenalty: Double?
  public var frequencyPenalty: Double?
  public var stopSequences: [String]?
  public var seed: Int?
  public var reasoning: LanguageModelV4ReasoningEffort?

  public init(
    model: LanguageModel? = nil,
    toolChoice: ToolChoice? = nil,
    activeTools: [String]? = nil,
    toolOrder: [String]? = nil,
    instructions: Instructions? = nil,
    messages: [ModelMessage]? = nil,
    toolsContext: [String: JSONValue]? = nil,
    providerOptions: ProviderOptions? = nil,
    maxOutputTokens: Int? = nil,
    temperature: Double? = nil,
    topP: Double? = nil,
    topK: Int? = nil,
    presencePenalty: Double? = nil,
    frequencyPenalty: Double? = nil,
    stopSequences: [String]? = nil,
    seed: Int? = nil,
    reasoning: LanguageModelV4ReasoningEffort? = nil
  ) {
    self.model = model
    self.toolChoice = toolChoice
    self.activeTools = activeTools
    self.toolOrder = toolOrder
    self.instructions = instructions
    self.messages = messages
    self.toolsContext = toolsContext
    self.providerOptions = providerOptions
    self.maxOutputTokens = maxOutputTokens
    self.temperature = temperature
    self.topP = topP
    self.topK = topK
    self.presencePenalty = presencePenalty
    self.frequencyPenalty = frequencyPenalty
    self.stopSequences = stopSequences
    self.seed = seed
    self.reasoning = reasoning
  }

  /// Applies the overrides to call settings. Mirrors upstream `prepareStepCallSettings`.
  func apply(to settings: CallSettings) -> CallSettings {
    var merged = settings
    merged.maxOutputTokens = maxOutputTokens ?? settings.maxOutputTokens
    merged.temperature = temperature ?? settings.temperature
    merged.topP = topP ?? settings.topP
    merged.topK = topK ?? settings.topK
    merged.presencePenalty = presencePenalty ?? settings.presencePenalty
    merged.frequencyPenalty = frequencyPenalty ?? settings.frequencyPenalty
    merged.stopSequences = stopSequences ?? settings.stopSequences
    merged.seed = seed ?? settings.seed
    merged.reasoning = reasoning ?? settings.reasoning
    return merged
  }
}

/// Prepares settings for each step. Mirrors upstream `PrepareStepFunction`.
public typealias PrepareStepFunction = @Sendable (PrepareStepOptions) async throws -> PrepareStepResult?

/// Which large payloads to keep in step results. Mirrors upstream `GenerateTextInclude`.
public struct IncludeOptions: Sendable, Equatable {
  public var requestBody: Bool
  public var requestMessages: Bool
  public var responseBody: Bool

  public init(requestBody: Bool = false, requestMessages: Bool = false, responseBody: Bool = false) {
    self.requestBody = requestBody
    self.requestMessages = requestMessages
    self.responseBody = responseBody
  }
}
