import Foundation

/// Content generated by a language model. Mirrors upstream `LanguageModelV4Content`.
public enum LanguageModelV4Content: Sendable, Equatable {
  case text(LanguageModelV4Text)
  case reasoning(LanguageModelV4Reasoning)
  case custom(LanguageModelV4CustomContent)
  case reasoningFile(LanguageModelV4ReasoningFile)
  case file(LanguageModelV4File)
  case toolApprovalRequest(LanguageModelV4ToolApprovalRequest)
  case source(LanguageModelV4Source)
  case toolCall(LanguageModelV4ToolCall)
  case toolResult(LanguageModelV4ToolResult)
}

/// Text that the model has generated. Mirrors upstream `LanguageModelV4Text`.
public struct LanguageModelV4Text: Sendable, Equatable {
  public var text: String
  public var providerMetadata: SharedV4ProviderMetadata?

  public init(text: String, providerMetadata: SharedV4ProviderMetadata? = nil) {
    self.text = text
    self.providerMetadata = providerMetadata
  }
}

/// Reasoning that the model has generated. Mirrors upstream `LanguageModelV4Reasoning`.
public struct LanguageModelV4Reasoning: Sendable, Equatable {
  public var text: String
  public var providerMetadata: SharedV4ProviderMetadata?

  public init(text: String, providerMetadata: SharedV4ProviderMetadata? = nil) {
    self.text = text
    self.providerMetadata = providerMetadata
  }
}

/// Provider-specific content. Mirrors upstream `LanguageModelV4CustomContent`.
public struct LanguageModelV4CustomContent: Sendable, Equatable {
  /// In the format `{provider}.{provider-type}`.
  public var kind: String
  public var providerMetadata: SharedV4ProviderMetadata?

  public init(kind: String, providerMetadata: SharedV4ProviderMetadata? = nil) {
    self.kind = kind
    self.providerMetadata = providerMetadata
  }
}

/// A file generated by the model. Mirrors upstream `LanguageModelV4File`.
public struct LanguageModelV4File: Sendable, Equatable {
  public var mediaType: String
  /// Raw bytes, base64 or URL.
  public var data: SharedV4FileData
  public var providerMetadata: SharedV4ProviderMetadata?

  public init(
    mediaType: String, data: SharedV4FileData, providerMetadata: SharedV4ProviderMetadata? = nil
  ) {
    self.mediaType = mediaType
    self.data = data
    self.providerMetadata = providerMetadata
  }
}

/// A file generated as part of reasoning. Mirrors upstream `LanguageModelV4ReasoningFile`.
public struct LanguageModelV4ReasoningFile: Sendable, Equatable {
  public var mediaType: String
  public var data: SharedV4FileData
  public var providerMetadata: SharedV4ProviderMetadata?

  public init(
    mediaType: String, data: SharedV4FileData, providerMetadata: SharedV4ProviderMetadata? = nil
  ) {
    self.mediaType = mediaType
    self.data = data
    self.providerMetadata = providerMetadata
  }
}

/// A request for approval of a provider-executed tool call.
/// Mirrors upstream `LanguageModelV4ToolApprovalRequest`.
public struct LanguageModelV4ToolApprovalRequest: Sendable, Equatable {
  public var approvalId: String
  public var toolCallId: String
  public var providerMetadata: SharedV4ProviderMetadata?

  public init(
    approvalId: String, toolCallId: String, providerMetadata: SharedV4ProviderMetadata? = nil
  ) {
    self.approvalId = approvalId
    self.toolCallId = toolCallId
    self.providerMetadata = providerMetadata
  }
}

/// A source used to generate the content. Mirrors upstream `LanguageModelV4Source`.
public enum LanguageModelV4Source: Sendable, Equatable {
  case url(id: String, url: String, title: String? = nil, providerMetadata: SharedV4ProviderMetadata? = nil)
  case document(
    id: String,
    mediaType: String,
    title: String,
    filename: String? = nil,
    providerMetadata: SharedV4ProviderMetadata? = nil)

  public var id: String {
    switch self {
    case .url(let id, _, _, _), .document(let id, _, _, _, _): id
    }
  }
}

/// A tool call the model has generated. Mirrors upstream `LanguageModelV4ToolCall`.
public struct LanguageModelV4ToolCall: Sendable, Equatable {
  public var toolCallId: String
  public var toolName: String
  /// Stringified JSON input. Might not be valid JSON.
  public var input: String
  /// Whether the provider executed the tool.
  public var providerExecuted: Bool?
  /// Whether the tool is dynamic, i.e. defined at runtime (e.g. an MCP tool).
  public var dynamic: Bool?
  public var providerMetadata: SharedV4ProviderMetadata?

  public init(
    toolCallId: String,
    toolName: String,
    input: String,
    providerExecuted: Bool? = nil,
    dynamic: Bool? = nil,
    providerMetadata: SharedV4ProviderMetadata? = nil
  ) {
    self.toolCallId = toolCallId
    self.toolName = toolName
    self.input = input
    self.providerExecuted = providerExecuted
    self.dynamic = dynamic
    self.providerMetadata = providerMetadata
  }
}

/// The result of a provider-executed tool call. Mirrors upstream `LanguageModelV4ToolResult`.
public struct LanguageModelV4ToolResult: Sendable, Equatable {
  public var toolCallId: String
  public var toolName: String
  /// The result. Must not be `null`.
  public var result: JSONValue
  public var isError: Bool?
  /// Preliminary results replace each other; the last one is the final result.
  public var preliminary: Bool?
  public var dynamic: Bool?
  public var providerMetadata: SharedV4ProviderMetadata?

  public init(
    toolCallId: String,
    toolName: String,
    result: JSONValue,
    isError: Bool? = nil,
    preliminary: Bool? = nil,
    dynamic: Bool? = nil,
    providerMetadata: SharedV4ProviderMetadata? = nil
  ) {
    self.toolCallId = toolCallId
    self.toolName = toolName
    self.result = result
    self.isError = isError
    self.preliminary = preliminary
    self.dynamic = dynamic
    self.providerMetadata = providerMetadata
  }
}

/// Why a language model finished generating. Mirrors upstream `LanguageModelV4FinishReason`.
public struct LanguageModelV4FinishReason: Sendable, Hashable {
  public enum Unified: String, Sendable, Hashable {
    case stop
    case length
    case contentFilter = "content-filter"
    case toolCalls = "tool-calls"
    case error
    case other
  }

  /// The unified finish reason.
  public var unified: Unified
  /// The raw finish reason from the provider.
  public var raw: String?

  public init(unified: Unified, raw: String? = nil) {
    self.unified = unified
    self.raw = raw
  }
}

/// Token usage. Mirrors upstream `LanguageModelV4Usage`.
public struct LanguageModelV4Usage: Sendable, Equatable {
  public struct InputTokens: Sendable, Hashable {
    /// Total input tokens.
    public var total: Int?
    /// Input tokens that were not read from or written to a cache.
    public var noCache: Int?
    /// Input tokens read from a cache.
    public var cacheRead: Int?
    /// Input tokens written to a cache.
    public var cacheWrite: Int?

    public init(total: Int? = nil, noCache: Int? = nil, cacheRead: Int? = nil, cacheWrite: Int? = nil) {
      self.total = total
      self.noCache = noCache
      self.cacheRead = cacheRead
      self.cacheWrite = cacheWrite
    }
  }

  public struct OutputTokens: Sendable, Hashable {
    /// Total output tokens.
    public var total: Int?
    /// Text tokens.
    public var text: Int?
    /// Reasoning tokens.
    public var reasoning: Int?

    public init(total: Int? = nil, text: Int? = nil, reasoning: Int? = nil) {
      self.total = total
      self.text = text
      self.reasoning = reasoning
    }
  }

  public var inputTokens: InputTokens
  public var outputTokens: OutputTokens
  /// Raw usage information from the provider.
  public var raw: JSONObject?

  public init(
    inputTokens: InputTokens = InputTokens(),
    outputTokens: OutputTokens = OutputTokens(),
    raw: JSONObject? = nil
  ) {
    self.inputTokens = inputTokens
    self.outputTokens = outputTokens
    self.raw = raw
  }
}

/// Response metadata. Mirrors upstream `LanguageModelV4ResponseMetadata`.
public struct LanguageModelV4ResponseMetadata: Sendable, Hashable {
  /// ID for the generated response, if the provider sends one.
  public var id: String?
  /// Timestamp for the start of the generated response.
  public var timestamp: Date?
  /// The ID of the response model that was used.
  public var modelId: String?

  public init(id: String? = nil, timestamp: Date? = nil, modelId: String? = nil) {
    self.id = id
    self.timestamp = timestamp
    self.modelId = modelId
  }
}
